local icons = {
  signs = {
   error = "",
   warn = "",
   hint = "",
   info = "",
   git = " ",
   searchProject = "󰺅",
   searchFiles = "󰱽",
   searchText = "󱎸",
   notebook = "",
   recentfiles = "󱋢",
   cog = "",
   org = "",
   checkmark = "",
   rightArrow = "",
   smallRightArrow = "",
   guillemet = "»",
   close = "",
   gitAdd = "|",
   gitDelete = "_",
   gitTopDelete = "‾",
   gitChangeDelete = "~",
   gitUntracked = "┆",
   telescope = "",
   caret = ">",
   cmd =  "",
   lightning = "",
   document = "",
   import = "",
   keyboard = "",
   sleep = "󰒲",
   filledOrb = "●",
   orb = "○",
   package = "󰏗",
   vim = "",
   code = "",
   play = "",
   star = "",
   line = "‒",
   ignored = "",
   unstaged = "",
   staged = "",
   conflict = "",
  },

  icons = {
    Class = "",
    Constructor = "",
    Function = "󰊕",
    Keyword = "",
    Method = "",
    Module = "",
    Field = "",
    Snippet = "󰘖",
    Text = "",
    Variable = "",
  },

  diagnosticSigns = {
    {name = "DiagnosticSignError", text = ""},
    {name = "DiagnosticSignWarn", text = ""},
    {name = "DiagnosticSignHint", text = ""},
    {name = "DiagnosticSignInfo", text = ""}
  },
}

return icons
